name: flutter_xiaomi_mall
version: 1.0.0+1
publish_to: none
description: A mall Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter_screenutil: ^5.9.0
  flutter_swiper_view: ^1.1.8
  dio: ^5.4.0
  flutter_staggered_grid_view: ^0.7.0
  pull_to_refresh_flutter3: ^2.0.2


  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  fonts:
    - family: myIcon   #指定一个字体名 根据自己的需求定义
      fonts:
        - asset: assets/fonts/iconfont.ttf     
  

  assets:
    - assets/images/xiaomiBanner.png


